apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: kuma-pv
  namespace: uptime-kuma
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/uptime-kuma"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-pvc
  namespace: uptime-kuma
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      volumes:
        - name: kuma-data
          persistentVolumeClaim:
            claimName: kuma-pvc
      containers:
      - image: louislam/uptime-kuma
        name: uptime-kuma
        ports:
        - containerPort: 3001
        volumeMounts:
          - name: kuma-data
            mountPath: /app/data
---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: uptime-kuma
#  labels:
#    app: uptime-kuma-ip
#  name: uptime-kuma-ip
#spec:
#  ports:
#  - name: uptime-kuma-clusterip
#    port: 3001
#    protocol: TCP
#    targetPort: 3001
#  selector:
#    app: uptime-kuma
#  type: ClusterIP
#  clusterIP: 10.103.233.56
